import unittest
from game_of_life import GameOfLife
from utils import parse_pattern
from textwrap import dedent

class TestGameOfLife(unittest.TestCase):
    def setUp(self):
        self.game = GameOfLife(10, 10)

    def test_cells_are_initialized_with_one_glider(self):
        self.assertEqual(str(self.game), dedent("""\
            ..........
            ..........
            ..........
            ..........
            .....#....
            ......#...
            ....###...
            ..........
            ..........
            .........."""))

    def test_glider_simulates_correctly(self):
        self.assertEqual(str(self.game), dedent("""\
            ..........
            ..........
            ..........
            ..........
            .....#....
            ......#...
            ....###...
            ..........
            ..........
            .........."""))

        self.game.simulate()
        self.assertEqual(str(self.game), dedent("""\
            ..........
            ..........
            ..........
            ..........
            ..........
            ....#.#...
            .....##...
            .....#....
            ..........
            .........."""))

        self.game.simulate()
        self.assertEqual(str(self.game), dedent("""\
            ..........
            ..........
            ..........
            ..........
            ..........
            ......#...
            ....#.#...
            .....##...
            ..........
            .........."""))
        
        self.game.simulate()
        self.assertEqual(str(self.game), dedent("""\
            ..........
            ..........
            ..........
            ..........
            ..........
            .....#....
            ......##..
            .....##...
            ..........
            .........."""))

        self.game.simulate()
        self.assertEqual(str(self.game), dedent("""\
            ..........
            ..........
            ..........
            ..........
            ..........
            ......#...
            .......#..
            .....###..
            ..........
            .........."""))
        
    def test_can_toggle_cell(self):
        x = 3
        y = 2
        
        self.assertEqual(self.game.get_cell(x, y), False)
        self.game.toggle_cell(x, y)
        self.assertEqual(self.game.get_cell(x, y), True)
        self.game.toggle_cell(x, y)
        self.assertEqual(self.game.get_cell(x, y), False)
        